name: CI

on:
  push:
    branches: [master, main]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: make ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"

      - name: Run Make CI
        run: make ci
